import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
  RedirectToSignIn
} from "@clerk/nextjs";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`$inter.className max-w-md m-auto my-8`}>
        <body>
          <header className="flex justify-between">
            <Link href="/" className="font-semibold">
              elddir
            </Link>
            <div>
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          <SignedIn>
            <div>{children}</div>
          </SignedIn>
          <SignedOut>
            <RedirectToSignIn />
          </SignedOut>
          {/* <footer className="py-8 text-center absolute bottom-0 left-0 w-full">Made by Bek Slambek</footer> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
